// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpknnxzsqwyylokmkjsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wa25ueHpzcXd5eWxva21ranNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Nzg2MzQsImV4cCI6MjA1ODE1NDYzNH0.6bkyFj6RrP_do6Z3JWBocmouxl_OEnq3cybVwCqXMwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);